### function calling
GET http://localhost:8080/chat/chat
    ?question=你是谁

### function calling
GET http://localhost:8080/chat/systemMessage
    ?question=订单号:11111111111


### function calling
GET http://localhost:8080/chat/assistant
    ?memoryId=1&question=退票


